import type { IVacancy } from "~/types";
import { WorkSchedule, EducationLevel, EmploymentType } from "~/types";

const data: IVacancy[] = [
    {
        title: "Фронтенд бағдарламашы",
        post: "Frontend Developer",
        category: "Ақпараттық технологиялар",
        from_salary: 120000,
        to_salary: 180000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.REMOTE,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: "1-3 жыл",
        },
        professional_skills: ["HTML", "CSS", "JavaScript", "Vue.js"],
        personal_skills: ["Коммуникабельдік", "Жауапкершілік", "Шығармашылық көзқарас"],
        address: "Қашықтан",
    },
    {
        title: "Сату менеджері",
        post: "Sales Manager",
        category: "Сату",
        from_salary: 80000,
        to_salary: null,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.SECONDARY,
            type_employment: EmploymentType.PART_TIME,
            internship: false,
            work_experience: "Тәжірибесіз",
        },
        professional_skills: ["Сату дағдылары", "Келіссөздер", "Клиенттермен жұмыс"],
        personal_skills: ["Мақсатқа ұмтылушылық", "Икемділік", "Командамен жұмыс"],
        address: "Алматы қ., Ленин көшесі, 12",
    },
    {
        title: "Жүк көлігінің жүргізушісі",
        post: "Truck Driver",
        category: "Көлік және логистика",
        from_salary: 70000,
        to_salary: 100000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.ROTATIONAL,
            education: EducationLevel.SECONDARY,
            type_employment: EmploymentType.TEMPORARY,
            internship: false,
            work_experience: "3-5 жыл",
        },
        professional_skills: ["Жүк көлігін басқару", "Жол ережелерін білу", "Техникалық қызмет көрсету"],
        personal_skills: ["Ұқыптылық", "Жауапкершілік", "Стрессқа төзімділік"],
        address: "Шымкент қ., Жеңіс көшесі, 10",
    },
    {
        title: "Бағдарламашы инженер",
        post: "Software Engineer",
        category: "Ақпараттық технологиялар",
        from_salary: 150000,
        to_salary: 250000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: "5-7 жыл",
        },
        professional_skills: ["C++", "Python", "Алгоритмдер мен мәліметтер құрылымы"],
        personal_skills: ["Аналитикалық ойлау", "Жауапкершілік", "Командамен жұмыс"],
        address: "Астана қ., Мәскеу көшесі, 45",
    },
    {
        title: "Графикалық дизайнер",
        post: "Graphic Designer",
        category: "Дизайн",
        from_salary: 60000,
        to_salary: 90000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.FLEXIBLE,
            education: EducationLevel.VOCATIONAL,
            type_employment: EmploymentType.FREELANCE,
            internship: false,
            work_experience: "1-3 жыл",
        },
        professional_skills: ["Adobe Photoshop", "Illustrator", "Figma"],
        personal_skills: ["Шығармашылық", "Коммуникабельдік", "Қысқа мерзімде жұмыс"],
        address: "Қашықтан",
    },
    {
        title: "Математика мұғалімі",
        post: "Mathematics Teacher",
        category: "Білім",
        from_salary: 50000,
        to_salary: 75000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: "1-3 жыл",
        },
        professional_skills: ["Оқыту", "Балалармен жұмыс", "Оқыту әдістері"],
        personal_skills: ["Төзімділік", "Коммуникабельдік", "Жауапкершілік"],
        address: "Қарағанды қ., Бауыржан көшесі, 7",
    },
    {
        title: "Бариста",
        post: "Barista",
        category: "Қызмет көрсету саласы",
        from_salary: 40000,
        to_salary: 60000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.PART_TIME,
            education: EducationLevel.NONE,
            type_employment: EmploymentType.PART_TIME,
            internship: false,
            work_experience: "Тәжірибесіз",
        },
        professional_skills: ["Кофе дайындау", "Клиенттерге қызмет көрсету"],
        personal_skills: ["Көңілділік", "Командада жұмыс істеу", "Энергиялылық"],
        address: "Ақтөбе қ., Мира көшесі, 22",
    },
    {
        title: "Заңгер",
        post: "Lawyer",
        category: "Құқықтану",
        from_salary: 100000,
        to_salary: 150000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.MASTER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: "3-5 жыл",
        },
        professional_skills: ["Азаматтық құқық", "Кеңес беру", "Шарт жұмыстары"],
        personal_skills: ["Ұқыптылық", "Ұйымдастырушылық", "Тәртіптілік"],
        address: "Өскемен қ., Пушкин көшесі, 34",
    },
    {
        title: "HR-менеджер",
        post: "HR Manager",
        category: "Кадрлар",
        from_salary: 70000,
        to_salary: 100000,
        currency: "KZT",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: "1-3 жыл",
        },
        professional_skills: ["Қызметкерлерді таңдау", "Адаптация", "Іс-шараларды ұйымдастыру"],
        personal_skills: ["Коммуникабельдік", "Жауапкершілік", "Энергиялылық"],
        address: "Павлодар қ., Ленин көшесі, 17",
    },
];

export const vacancy_kk: IVacancy[] = data;
